### ISSUE TITLE
where is args.txt?

### ISSUE THREAD

**Issue by AlbertTan404** [LayoutLLM-T2I/LayoutLLM-T2I#5]
Hi! Thanks for your novel work.
I'm trying to run txt2img.py and downloaded the checkpoints from google and baidu drive. But there are two questions I'm concerning:
1. should the argument 'policy_ckpt_path' in `txt2img.py` [line 523](https://github.com/LayoutLLM-T2I/LayoutLLM-T2I/blob/bffce5123c58205776168b75dafa3f8d09f8e58f/txt2img.py#L523C27-L523C28) be 'policy_ckpt_dir'?
2. And in the following lines, there requires an args.txt but the POLICY_CKPT seems only concludes a .pt file, where can we find it?

**Comment by LgQu** [comment]
Hi, 
Sorry for the confusion. We have added args.txt in the configs directory,  and revised the corresponding part to make the code clearer.
